import SwiftUI

func posterURL(_ path: String?) -> URL? { path.flatMap { URL(string: "https://image.tmdb.org/t/p/w500\($0)") } }
struct Poster: View { let path: String?; var width: CGFloat = 66; var body: some View { AsyncImage(url: posterURL(path)) { $0.resizable().scaledToFill() } placeholder: { Rectangle().fill(SceneTheme.raised).overlay(Image(systemName: "film").foregroundStyle(SceneTheme.muted)) }.frame(width: width, height: width * 1.48).clipped() } }
struct PosterCard: View { let media: MediaRecord; let subtitle: String; var badge: String?; var progress: Double?; var body: some View { VStack(alignment: .leading, spacing: 8) { ZStack(alignment: .topLeading) { Poster(path: media.posterPath, width: 142); if let badge { Text(badge).font(.system(size: 9, weight: .black)).tracking(0.6).foregroundStyle(SceneTheme.canvas).padding(.horizontal, 8).padding(.vertical, 7).background(SceneTheme.yellow) } }.overlay(Rectangle().stroke(SceneTheme.line)); Text(media.title).font(.system(.headline, design: .serif)).lineLimit(1); Text(subtitle).font(.caption).foregroundStyle(SceneTheme.muted).lineLimit(1); if let progress { VStack(alignment: .leading, spacing: 5) { Text("\(Int(progress))% watched").font(.caption2).foregroundStyle(SceneTheme.muted); GeometryReader { proxy in Rectangle().fill(SceneTheme.line).overlay(alignment: .leading) { Rectangle().fill(SceneTheme.yellow).frame(width: proxy.size.width * min(progress, 100) / 100) } }.frame(height: 3) }.frame(width: 142) } }.frame(width: 142, alignment: .leading) } }
struct SceneMediaRow: View { let media: MediaRecord; var trailing: String? = nil; init(media: MediaRecord, trailing: String? = nil) { self.media = media; self.trailing = trailing }; init(media: SearchResult) { self.media = MediaRecord(id: media.id, kind: media.kind, tmdbId: media.tmdbId, title: media.title, originalTitle: media.originalTitle, releaseYear: media.releaseYear, overview: media.overview, posterPath: media.posterPath, backdropPath: nil, status: nil, runtime: nil, seriesId: nil, seasonNumber: nil, episodeNumber: nil, airDate: nil, metadataUpdatedAt: "") }; var body: some View { SceneCard { HStack(spacing: 12) { Poster(path: media.posterPath); VStack(alignment: .leading, spacing: 5) { Text(media.title).font(.headline); Text(media.releaseYear.map(String.init) ?? media.kind.rawValue.capitalized).font(.caption.weight(.semibold)).foregroundStyle(SceneTheme.yellow); if let overview = media.overview { Text(overview).lineLimit(2).font(.caption).foregroundStyle(SceneTheme.muted) } }; Spacer(); VStack(alignment: .trailing) { if let trailing { Text(trailing).font(.caption2).foregroundStyle(SceneTheme.muted) }; Image(systemName: "chevron.right").font(.caption.weight(.bold)).foregroundStyle(SceneTheme.muted) } } } } }

struct DetailView: View {
    let kind: MediaKind; let tmdbId: Int
    @State private var detail: MediaDetail?; @State private var error: String?; @State private var watchedAt = Date()
    var body: some View { SceneScreen { ScrollView { if let d = detail { VStack(alignment: .leading, spacing: 22) { hero(d); tracking(d); if kind == .show { episodes(d) }; history(d) }.padding(.vertical, 18) } else if let error { ContentUnavailableView("Unable to load", systemImage: "wifi.exclamationmark", description: Text(error)).frame(maxWidth: .infinity, minHeight: 360) } else { ProgressView().frame(maxWidth: .infinity, minHeight: 360) } }.refreshable { await load() } }.navigationBarTitleDisplayMode(.inline).task { await load() } }
    private func hero(_ d: MediaDetail) -> some View { HStack(alignment: .top, spacing: 16) { Poster(path: d.media.posterPath, width: 122).overlay(Rectangle().stroke(SceneTheme.line)); VStack(alignment: .leading, spacing: 8) { Text(d.media.kind.rawValue.uppercased()).font(.caption2.weight(.black)).tracking(1.5).foregroundStyle(SceneTheme.yellow); Text(d.media.title).font(.system(.title, design: .serif).weight(.bold)); if let year = d.media.releaseYear { Text("\(year)").font(.caption).foregroundStyle(SceneTheme.muted) }; Text(d.media.overview ?? "").lineLimit(7).font(.caption).foregroundStyle(SceneTheme.muted) } } }
    private func tracking(_ d: MediaDetail) -> some View { VStack(alignment: .leading, spacing: 12) { SceneSectionTitle(eyebrow: "Your record", title: "Tracking"); SceneCard { VStack(alignment: .leading, spacing: 14) { DatePicker("Watched on", selection: $watchedAt, displayedComponents: .date); Button { watch(d.media.id, watchedAt) } label: { Label("Mark watched", systemImage: "checkmark.circle.fill").frame(maxWidth: .infinity) }.buttonStyle(.borderedProminent).tint(SceneTheme.yellow).foregroundStyle(SceneTheme.canvas); HStack { Button(d.inWatchlist ? "Remove from watchlist" : "Add to watchlist") { toggleWatchlist(d.media.id, d.inWatchlist) }; Spacer(); Menu { Button("Clear rating") { rate(0, d.media.id) }; ForEach(1...10, id: \.self) { value in Button("\(value) / 10") { rate(value, d.media.id) } } } label: { Label(d.rating.map { "\($0) / 10" } ?? "Rate", systemImage: "star") } } } } } }
    private func episodes(_ d: MediaDetail) -> some View { VStack(alignment: .leading, spacing: 12) { SceneSectionTitle(eyebrow: "Progress", title: "Episodes"); ForEach(d.episodes) { episode in Button { watch(episode.id, Date()) } label: { SceneCard { HStack { Text("S\(episode.seasonNumber ?? 0) E\(episode.episodeNumber ?? 0)").font(.caption.weight(.black)).foregroundStyle(SceneTheme.yellow); Text(episode.title).lineLimit(1); Spacer(); Image(systemName: d.watchEvents.contains(where: { $0.mediaId == episode.id }) ? "checkmark.circle.fill" : "circle").foregroundStyle(d.watchEvents.contains(where: { $0.mediaId == episode.id }) ? .green : SceneTheme.muted) } } } } } }
    private func history(_ d: MediaDetail) -> some View { VStack(alignment: .leading, spacing: 12) { if !d.watchEvents.isEmpty { SceneSectionTitle(eyebrow: "The log", title: "Recent watches"); ForEach(d.watchEvents) { event in SceneCard { HStack { Text(String(event.watchedAt.prefix(10))).foregroundStyle(SceneTheme.muted); Spacer(); Button(role: .destructive) { undo(event.id) } label: { Label("Undo", systemImage: "arrow.uturn.backward") } } } } } } }
    private func load() async { do { detail = try await APIClient.shared.request("/api/media/\(kind.rawValue)/\(tmdbId)", cacheKey: "media-\(kind)-\(tmdbId)") } catch { self.error = error.localizedDescription } }
    private func watch(_ id: String, _ date: Date) { Task { do { let _: WatchEventResponse = try await APIClient.shared.request("/api/watch-events", method: "POST", body: WatchRequest(mediaId: id, watchedAt: ISO8601DateFormatter().string(from: date))); await load() } catch { self.error = error.localizedDescription } } }
    private func undo(_ id: String) { Task { try? await APIClient.shared.noContent("/api/watch-events/\(id)", method: "DELETE"); await load() } }
    private func toggleWatchlist(_ id: String, _ present: Bool) { Task { do { if present { try await APIClient.shared.noContent("/api/watchlist/\(id)", method: "DELETE") } else { let _: WatchlistResponse = try await APIClient.shared.request("/api/watchlist/\(id)", method: "PUT", body: EmptyRequest()) }; await load() } catch { self.error = error.localizedDescription } } }
    private func rate(_ rating: Int, _ id: String) { Task { do { if rating == 0 { try await APIClient.shared.noContent("/api/ratings/\(id)", method: "DELETE") } else { let _: RatingResponse = try await APIClient.shared.request("/api/ratings/\(id)", method: "PUT", body: RatingRequest(rating: rating)) }; await load() } catch { self.error = error.localizedDescription } } }
}
private struct WatchRequest: Encodable { let mediaId: String; let watchedAt: String }; private struct RatingRequest: Encodable { let rating: Int }; private struct EmptyRequest: Encodable {}; private struct WatchEventResponse: Decodable { let event: WatchEvent? }; private struct RatingResponse: Decodable { let rating: Int }; private struct WatchlistResponse: Decodable { let inWatchlist: Bool }
